# Generated by Django 4.2.11 on 2026-06-02 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='作品描述')),
                ('image', models.ImageField(upload_to='artworks/', verbose_name='作品图片')),
                ('prompt', models.TextField(blank=True, default='', verbose_name='AI提示词')),
                ('ai_type', models.CharField(choices=[('cv', '计算机视觉'), ('llm', '大语言模型'), ('aigc', 'AI生成内容'), ('workshop', '创意工坊')], max_length=20, verbose_name='AI类型')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gallery.artwork', verbose_name='作品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LikeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_records', to='gallery.artwork', verbose_name='作品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞记录',
                'verbose_name_plural': '点赞记录',
                'unique_together': {('artwork', 'user')},
            },
        ),
    ]
