# Generated by Django 4.2.11 on 2026-06-02 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('project_type', models.CharField(choices=[('identify', '智能识物'), ('writing', 'AI写作'), ('painting', 'AI绘画'), ('workshop', '创意工坊')], max_length=20, verbose_name='项目类型')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='输出数据')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/', verbose_name='结果图片')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '创意项目',
                'verbose_name_plural': '创意项目',
                'ordering': ['-created_at'],
            },
        ),
    ]
